version: 2

sources:
  - name: dagster
    description: Raw data from Einstein
    schema: arboviroses
    tables:
      - name: einstein_raw
        meta:
          dagster:
            asset_key: ["einstein_raw"]