name: Deploy code to server
on: 
  push:
    branches:
      - master
      - dev-ci
  workflow_dispatch:
  
jobs:
  deploy-ci:
    runs-on: ubuntu-latest
    steps:
      - name: configure SSH credentials
        run: echo "Configuring SSH credentials"
      - run: echo -e '\x1dclose\x0d' | telnet ${{ secrets.HOST_IP }} 80
      - run: sleep 5
      - run: |
            mkdir -p ~/.ssh/
            echo "{{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
      - run: echo "Host remotehost\n\tStrictHostKeyChecking no\n" >> /home/user/.ssh/config
      - run: ssh ${{ secrets.HOST_USER }}@${{ secrets.HOST_IP }} 'echo Hello!'
