name: Deploy code to server
on: 
  push:
    branches:
      - master
      - dev-ci
  workflow_dispatch:
  
jobs:
  deploy-ci:
    runs-on: ubuntu-latest
    steps:
      - name: configure SSH credentials
        run: echo "Configuring SSH credentials"
      - run: echo -e '\x1dclose\x0d' | telnet ${{ secrets.HOST_IP }} 80
      - run: sleep 5
