name: Deploy code to server
on: 
  push:
    branches:
      - master
      - dev-ci
  workflow_dispatch:
  
jobs:
  deploy-ci:
    runs-on: ubuntu-latest
    steps:
      - name: configure SSH credentials
        run: echo "Configuring SSH credentials "
      - run: echo -e '\x1dclose\x0d' | telnet ${{ secrets.HOST_IP }} 80
      - run: |
          echo "$SSH_KEY" > private.key
      - run: ssh -i private.key ${{ secrets.HOST_USER }}@${{ secrets.HOST_IP }} 'echo Hello!'
        env:
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
