name: Deploy code to server
on: 
  push:
    branches:
      - master
      - dev-ci
  workflow_dispatch:
  
jobs:
  deploy-ci:
    runs-on: ubuntu-latest
    steps:
      - name: configure SSH credentials
      - run: ping -c 10 ${{ secrets.HOST_IP }}
      - run: sleep 5
